import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#490006',
        'inverse-primary': '#005bc2',
        'on-background': '#ffffff',
        'surface-container-high': '#20201f',
        'inverse-surface': '#fcf9f8',
        'on-primary-fixed-variant': '#002a61',
        tertiary: '#fab0ff',
        'tertiary-fixed-dim': '#e48fec',
        'on-surface': '#ffffff',
        'surface-variant': '#262626',
        'secondary-container': '#006c49',
        'on-tertiary': '#6b1f77',
        'surface-tint': '#85adff',
        'tertiary-dim': '#e48fec',
        'surface-container-highest': '#262626',
        'secondary-fixed-dim': '#58e7ab',
        'on-tertiary-fixed-variant': '#6a1f76',
        'on-secondary-fixed': '#00452d',
        'primary-fixed': '#6c9fff',
        'on-tertiary-container': '#60136d',
        'on-secondary-container': '#e1ffec',
        'primary-fixed-dim': '#5191ff',
        'on-primary': '#002c65',
        'surface-container-low': '#131313',
        'on-tertiary-fixed': '#41004d',
        'on-primary-container': '#00214f',
        'error-dim': '#d7383b',
        'on-primary-fixed': '#000000',
        'secondary-dim': '#58e7ab',
        'inverse-on-surface': '#565555',
        'tertiary-fixed': '#f39cfb',
        'surface-dim': '#0e0e0e',
        'on-surface-variant': '#adaaaa',
        primary: '#85adff',
        secondary: '#69f6b8',
        error: '#ff716c',
        'primary-container': '#6c9fff',
        'surface-container': '#1a1a1a',
        'on-error-container': '#ffa8a3',
        'secondary-fixed': '#69f6b8',
        'primary-dim': '#0070eb',
        'tertiary-container': '#f39cfb',
        'on-secondary': '#005a3c',
        outline: '#767575',
        'outline-variant': '#484847',
        'error-container': '#9f0519',
        background: '#0e0e0e',
        'surface-bright': '#2c2c2c',
        surface: '#0e0e0e',
        'surface-container-lowest': '#000000',
        'on-secondary-fixed-variant': '#006544',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}

export default config
